// Side-effect CSS imports (`import "./globals.css"` in layout.tsx and
// global-error.tsx) have no type declaration of their own under
// moduleResolution "bundler", so `tsc --noEmit` reports TS2882 on both.
//
// This is not something Next supplies: `next/types/global.d.ts` declares
// `*.module.css` and `*.module.scss` only, never a plain stylesheet. `next
// build` passes regardless, because it runs its own type check that already
// understands the import — so the failure is visible ONLY to a standalone
// `npx tsc --noEmit`, which is exactly the check a session runs to decide
// whether the tree is clean.
//
// It was invisible for a long time because a stale artifact from an older Next
// version was sitting in `.next/` and declaring it. That file is not tracked,
// is not regenerated by Next 15.5, and vanished the moment `.next` was cleared
// on 2026-09-05 — at which point tsc started failing on an untouched checkout.
// Declaring it here makes the guarantee real and independent of build output.
declare module "*.css";
